### PR TITLE
Misc. datadriven improvements

### PR DESCRIPTION
**Pull request by knz**
See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/datadriven/2)

### CODE REVIEW

**Comment by knz** [comment]
I'd be glad to receive a second opinion on this, e.g. @RaduBerinde who was making changes recently in this area.

**Comment by knz** [comment]
Thanks to both for the review!

**Comment by RaduBerinde** [comment]
___
*[datadriven_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/datadriven/2#-LteQB_B7bmiQz7l4wV3:-LtemcJo-QbRowLcxwoU:b-xyjolm) ([raw file](https://github.com/cockroachdb/datadriven/blob/8e2cf0e8470cc67ea0f2daeea62914205dda0651/datadriven_test.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I strongly disagree - I am relying on the current behavior elsewhere. Also I'm not keen on introducing code to de-duplicate when it's not going to be useful in 80% of the cases.

I'll document the behavior as part of the API.
</blockquote></details>

Out of curiosity, what's your use case? I can't think of why you would want to do that (short of auto-generated test files or something), but maybe I lack imagination.

**Comment by knz** [comment]
> Out of curiosity, what's your use case?

Here: https://github.com/cockroachdb/cockroach/pull/42250

**Comment by RaduBerinde** [comment]
Interesting, though I still don't see where/why you would specify the same argument multiple times.

**Comment by knz** [comment]
> Interesting, though I still don't see where/why you would specify the same argument multiple times.

Consider this:

```
with k=mykey
   put v=1
   put v=abc k=other # interleave a write on another key
   put v=2
   get
```

We want to omit/share the k=mykey as much as possible, but enable a temporary override where relevant.

This is implemented by _appending_ the `[]CmdArg` array specified by `with` to the CmdArgs of each subsequent directive, and relying on the "first match wins" rule to guarantee proper scoping/prioritization.

**Comment by RaduBerinde** [comment]
This is not an argument for the correct semantics, it's an implementation detail. You could easily have a `with`-specific function that removes duplicates instead of a simple append. You'd still want to disallow duplicate args within each directive, eg `put v=1 k=other v=2`.

**Comment by RaduBerinde** [comment]
Or, you could leave the "prefer first entry" logic in place but still error out if you see the same value in a single directive.

**Comment by knz** [comment]
Yes ok that's true. But do you think it's worth to add the extra logic to detect duplicates, where in the common case this will not occur?

**Comment by knz** [comment]
Actually I like it, it's not even super expensive to do.

**Pull request merged**
