### PR TITLE
Support providing a callback to wrap the error message.

### PR DESCRIPTION
**Pull request by RichardJCai**
This allows some flexibility in adding more information if the
actual output does not match the expected output.

Motivation for this PR is here - https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94, want to make it possible to provide the trace if the test fails.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/datadriven/25)

### CODE REVIEW

**Comment by knz** [comment]
I don't think you need this. 
The `t.Fatal` call operates using a Go panic. You can use `defer` and `if r := recover()` in your datadriven runner in https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94 to attach your trace without modifying datadriven (I think)

**Comment by RichardJCai** [comment]
> I don't think you need this.
> The `t.Fatal` call operates using a Go panic. You can use `defer` and `if r := recover()` in your datadriven runner in https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94 to attach your trace without modifying datadriven (I think)

Ah I didn't know about that pattern I'll give it a try.

**Comment by RichardJCai** [comment]
> I don't think you need this.
> The `t.Fatal` call operates using a Go panic. You can use `defer` and `if r := recover()` in your datadriven runner in https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94 to attach your trace without modifying datadriven (I think)

I can't seem to get this to work, it seems like the goroutine calling panic isn't the one where defer is being called.

**Comment by tbg** [comment]
testing uses `runtime.Goexit()`, which returns `nil` from `recover()`.
There are tricks to make it work but it's not great.

**Comment by RichardJCai** [comment]
> testing uses `runtime.Goexit()`, which returns `nil` from `recover()`. There are tricks to make it work but it's not great.

Ah I see, that's probably not preferred then. What are your thoughts on this PR?

**Comment by tbg** [comment]
I'm not a fan of this PR. It really messes up the interface - we could use an option pattern to make this invisible when unused but I don't see enough evidence that this is worthy of inclusion in the library itself. Does this simple pattern solve your use case?

https://play.golang.com/p/Ul4CH7CTTAb

```go
package main

import (
	"testing"
)

func mayFatal(t *testing.T) {
	t.Fatal("boom")
}

func TestLastIndex(t *testing.T) {
	fataled := true
	defer func() {
		if fataled {
			t.Log("here's your trace")
		}
	}()

	mayFatal(t)
	fataled = false
}
```

**Comment by knz** [comment]
cc @RaduBerinde who has a bit more experience and may be able to profer more opinions/suggestions

**Comment by RaduBerinde** [comment]
I am not sure I understand the usecase. In https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94 the Fatalf message will already include the trace (since it's an assertion failure).

**Comment by RichardJCai** [comment]
> I am not sure I understand the usecase. In https://github.com/cockroachdb/cockroach/pull/50393/files#diff-956a6f65226eb90f50695e6d8f867a43R94 the Fatalf message will already include the trace (since it's an assertion failure).

I'm trying to add more information to the error message if the counts do not equal (adding the kv trace)

**Comment by RaduBerinde** [comment]
Would it be ok to always add the info if the test fails? That could be a `defer() { if t.Failed() { .. } }()` in the main test

**Comment by RichardJCai** [comment]
> Would it be ok to always add the info if the test fails? That could be a `defer() { if t.Failed() { .. } }()` in the main test

Yeah I think I might be able to get it to work with this.

**Comment by RichardJCai** [comment]
Closing this PR.

**Pull request closed without merging**
