### PR TITLE
Enable modules

### PR DESCRIPTION
**Pull request by tbg**
Fixes non-vendored dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/datadriven/12)

### CODE REVIEW

**Comment by tbg** [comment]
Something is broken here anyway. I have to look some more. Somehow the testdata are not available to the test binary; I hope this isn't some general fallout from the transition to modules (it makes sense that the module framework would run the test binary in isolation).

**Comment by knz** [comment]
> I hope this isn't some general fallout from the transition to modules

:crying_cat_face: I fear.

**Comment by tbg** [comment]
I also have this behavior with `GO111MODULE=off` though O_O

**Comment by tbg** [comment]
Ah nevermind. It's a bug in the temp file omit thing that you introduced recently. Will add a commit

**Comment by tbg** [comment]
> What does the go 1.13 directive say? Does it restrict the mod information to builds using 1.13?

Should be harmless:

> The go directive in a go.mod file now indicates the version of the language used by the files within that module. It will be set to the current release (go 1.12) if no existing version is present. If the go directive for a module specifies a version newer than the toolchain in use, the go command will attempt to build the packages regardless, and will note the mismatch only if that build fails. 

TFTR!

**Pull request merged**
